#默认使用配置
spring:
  profiles:
      active: dev

#公共配置与profiles选择无关
mybatis:
    mapper-locations: classpath:**/mapper/*.xml

logging:
  level:
     com.thorn.springboost.dao : debug
---

#开发配置
spring:
  profiles: dev

  datasource:
    url: jdbc:mysql://localhost:3306/test?serverTimezone=GMT%2B8&characterEncoding=utf-8
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver
  mvc:
    view:
      prefix: /WEB-INF/view/
      suffix: .jsp

  thymeleaf:
    cache: false
    enabled: false

logging:
  config: classpath:log4j2.yml
  level:
    com:
      looedu:
        mapper: debug

